name: Welcome New Users
description: 💖 Welcomes new users by creating a comment in the first time issue/PR
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication.
    required: false
    default: ${{ github.token }}

  FIRST_ISSUE:
    description: Comment to be posted to on first time issues.
    required: false

  FIRST_ISSUE_COMMENT:
    description: Comment to be posted to on first time issues.
    required: false

  FIRST_ISSUE_REACTIONS:
    description: Reactions to be add to comment on first time issues.
    required: false

  FIRST_PR:
    description: Comment to be posted to on PRs from first time contributors in your repository.
    required: false

  FIRST_PR_COMMENT:
    description: Comment to be posted to on PRs from first time contributors in your repository.
    required: false

  FIRST_PR_REACTIONS:
    description: Reactions to be add to comment on PRs from first time contributors in your repository.
    required: false

  FIRST_PR_MERGED:
    description: Comment to be posted to on pull requests merged by a first time user.
    required: false

  FIRST_PR_MERGED_COMMENT:
    description: Comment to be posted to on pull requests merged by a first time user.
    required: false

  FIRST_PR_MERGED_REACTIONS:
    description: Reactions to be add to comment on pull requests merged by a first time user.
    required: false

  STAR_MESSAGE:
    description: Message in the comment to tip non-stargazers to star our repo.
    required: false

runs:
  using: node20
  main: dist/index.js

branding:
  icon: heart
  color: green
